import {test} from 'node:test';import assert from 'node:assert/strict';import {publicIP,safeURL,cleanHTML,assess} from '../lib/reader.js';
test('rejects internal targets',async()=>{for(const x of ['127.0.0.1','10.0.0.1','169.254.169.254','::1','::ffff:127.0.0.1','192.168.1.1'])assert.equal(publicIP(x),false);assert.equal(publicIP('8.8.8.8'),true);for(const x of ['http://localhost','file:///etc/passwd','http://127.0.0.1','http://[::1]','https://a:b@example.com'])await assert.rejects(safeURL(x));});
test('login only is not page content; useful content survives login chrome',()=>{assert.notEqual(assess('Log into Facebook Email Password Create account','https://facebook.com/a').status,'read');const t='Log into Facebook\nعيادة الطبيب\n402K followers\nIntro\n'+('استشاري متخصص ومعلومات عن الخدمات والمواعيد. '.repeat(8));assert.equal(assess(t,'https://facebook.com/a').status,'read');assert.equal(assess('You’re Temporarily Blocked','https://facebook.com/a').status,'blocked');});
test('cleaner discards scripts/forms and resolves links',()=>{const x=cleanHTML('<html><title>Clinic</title><body><form>Password</form><script>secret()</script><p>Our clinic services and opening hours</p><a href="/about">About</a></body></html>','https://example.com');assert(!x.text.includes('Password'));assert(!x.text.includes('secret'));assert.equal(x.links[0].url,'https://example.com/about');});
import {cleanVisible,usefulLinks} from '../lib/reader.js';
test('partial social output excludes login and error chrome',()=>{const x=cleanVisible("Log In\nدكتور العيلة\n402K followers\nThis page isn't available right now\nPassword\nCreate new account");assert.equal(x,'دكتور العيلة\n402K followers');assert.equal(usefulLinks([{url:'https://facebook.com/login/'},{url:'https://facebook.com/reel/123'}]).length,1);});

test('page description from meta tags is used when the body has no text (JS-rendered pages)',()=>{const x=cleanHTML('<html><head><title>Dr Page</title><meta property="og:title" content="دكتور العيلة - د. عمرو عبد العزيز"><meta property="og:description" content="&#x200e;دكتور العيلة. 402K likes. جراح أمراض النساء والتوليد واستشاري الحقن المجهري"></head><body><div id="root"></div></body></html>','https://www.facebook.com/x');assert.match(x.text,/402K likes/);assert.match(x.text,/دكتور العيلة - د. عمرو/);assert.equal(x.fromMeta,true);const y=cleanHTML('<html><head><meta name="description" content="short"></head><body><p>'+'نص طويل كفاية عن خدمات العيادة. '.repeat(30)+'</p></body></html>','https://example.com');assert.equal(y.fromMeta,false);assert.doesNotMatch(y.text,/short/);});

import {cleanBrowserTmp} from '../lib/reader.js';import {mkdtemp,mkdir,writeFile,readdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
test('leftover browser profiles are removed from tmp, other files are kept',async()=>{const d=await mkdtemp(join(tmpdir(),'rt-'));await mkdir(join(d,'playwright_chromiumdev_profile-abc'));await writeFile(join(d,'core.123'),'x');await writeFile(join(d,'chromium'),'binary');await cleanBrowserTmp(d);assert.deepEqual(await readdir(d),['chromium']);});
