import dns from 'node:dns/promises';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
export const READER_BUILD='3.34.0';
import ipaddr from 'ipaddr.js';
import * as cheerio from 'cheerio';
export const BROWSER_HEADERS={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36','Accept-Language':'ar,en;q=0.8'};
export function publicIP(address){try{const a=ipaddr.process(address);return a.range()==='unicast';}catch{return false;}}
export async function safeURL(value){const u=new URL(value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||(u.port&&!['80','443'].includes(u.port)))throw Error('Only public HTTP(S) URLs are supported');const host=u.hostname.replace(/^\[|\]$/g,'');if(host==='localhost'||host.endsWith('.local')||host.endsWith('.internal'))throw Error('Private address rejected');const ips=ipaddr.isValid(host)?[{address:host}]:await dns.lookup(host,{all:true});if(!ips.length||ips.some(x=>!publicIP(x.address)))throw Error('Private address rejected');u.hash='';return u.href;}
export async function fetchPage(url){for(let n=0;n<5;n++){url=await safeURL(url);const social=/(^|\.)(facebook|instagram)\.com$/.test(new URL(url).hostname);const r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(12000),headers:social?{Accept:'text/html,text/plain'}:{...BROWSER_HEADERS,Accept:'text/html,application/xhtml+xml,text/plain;q=0.9,*/*;q=0.8'}});if(r.status>=300&&r.status<400&&r.headers.get('location')){url=new URL(r.headers.get('location'),url).href;continue;}if(!r.ok)throw Error('HTTP '+r.status);if(!/text\/|application\/xhtml/.test(r.headers.get('content-type')||''))throw Error('Unsupported content type');const reader=r.body.getReader();let size=0,parts=[];for(;;){const x=await reader.read();if(x.done)break;size+=x.value.length;if(size>1500000){await reader.cancel();throw Error('Page too large');}parts.push(Buffer.from(x.value));}return {url,html:Buffer.concat(parts).toString('utf8')};}throw Error('Too many redirects');}
export function cleanHTML(html,url){const $=cheerio.load(html);const title=$('title').text().trim();const meta=[...new Set(['og:title','og:description','description'].map(n=>String($(`meta[property="${n}"],meta[name="${n}"]`).first().attr('content')||'').replace(/[‎‏]/g,'').trim()).filter(Boolean))];$('script,style,noscript,svg,nav,footer,form,input,select').remove();$('br').replaceWith('\n');$('p,div,article,section,h1,h2,h3,li').append('\n');const body=$('body').text().split('\n').map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean).join('\n');const text=body.length<400&&meta.length?[...meta,body].filter(Boolean).join('\n'):body;const links=[];$('a[href]').each((_,a)=>{try{const u=new URL($(a).attr('href'),url);if(/^https?:$/.test(u.protocol)&&!u.username&&!u.password)links.push({url:u.href,label:$(a).text().trim().slice(0,160)});}catch{}});return {title,text,meta,fromMeta:body.length<400&&meta.length>0,links:[...new Map(links.map(x=>[x.url,x])).values()].slice(0,80)};}
export function assess(text,url){const t=String(text||'');if(/you.re temporarily blocked|automated (?:queries|traffic)|verify you are human|captcha|checking your browser|unusual traffic/i.test(t))return {status:'blocked',reason:'الموقع طلب تحقق أو حظر القراءة الآلية'};const social=/(^|\.)(facebook|instagram)\.com$/.test(new URL(url).hostname);const useful=social?/(?:followers|متابع|Intro|نبذة|ريلز|Reels|Shared with Public|استشاري|عيادة|Clinic)/i.test(t)&&t.length>180:t.length>180;if(useful)return {status:'read',reason:''};return {status:'unavailable',reason:/log in|log into|sign in|تسجيل الدخول/i.test(t)?'ظهرت صفحة دخول بدون محتوى كافٍ':'لم يظهر محتوى كافٍ للتحليل'};}
let browserPromise=null;
export async function cleanBrowserTmp(dir=os.tmpdir()){for(const f of await fs.readdir(dir).catch(()=>[]))if(/^playwright[-_]|^\.org\.chromium|^core\.|^Crashpad|^chromium-crash/i.test(f))await fs.rm(path.join(dir,f),{recursive:true,force:true}).catch(()=>{});}
async function getBrowser(){if(browserPromise){const b=await browserPromise.catch(()=>null);if(b&&b.isConnected())return b;}// Local runs (tests, development) can point at an installed Chromium with CHROME_PATH.
if(process.env.CHROME_PATH){const {chromium:pw}=await import('playwright-core');browserPromise=pw.launch({executablePath:process.env.CHROME_PATH,headless:true,...(process.env.READER_PROXY?{proxy:{server:process.env.READER_PROXY}}:{})});return browserPromise;}
const [{chromium:pw},{default:chromium}]=await Promise.all([import('playwright-core'),import('@sparticuz/chromium')]);// --single-process (meant for Puppeteer) makes Chromium exit when a Playwright context closes, so every later request failed.
await cleanBrowserTmp();browserPromise=pw.launch({args:[...chromium.args.filter(a=>a!=='--single-process'),'--disk-cache-size=1048576','--media-cache-size=1048576','--disable-breakpad'],executablePath:await chromium.executablePath(),headless:true});return browserPromise;}
export async function browserPage(url,opts={}){try{return await browserPageOnce(url,opts);}catch(e){if(!/ERR_INSUFFICIENT_RESOURCES|Target .*closed|Browser has been closed|browser has disconnected/i.test(String(e?.message||e)))throw e;const old=browserPromise;browserPromise=null;await old?.then(b=>b.close()).catch(()=>{});return browserPageOnce(url,opts);}}
async function browserPageOnce(url,opts={}){const browser=await getBrowser();let context;try{context=await browser.newContext({serviceWorkers:'block',ignoreHTTPSErrors:!!process.env.READER_PROXY,acceptDownloads:false,userAgent:BROWSER_HEADERS['User-Agent'],locale:'ar-EG'});const validated=new Map();await context.route('**/*',async route=>{const req=route.request();if(!['GET','HEAD'].includes(req.method())||['image','media','font'].includes(req.resourceType()))return route.abort();try{const u=req.url();if(!validated.has(new URL(u).origin))validated.set(new URL(u).origin,await safeURL(u));await route.continue();}catch{await route.abort();}});const page=await context.newPage();await page.goto(await safeURL(url),{waitUntil:'domcontentloaded',timeout:25000});await page.locator('body').waitFor({timeout:8000});let raw=await page.locator('body').innerText();if(assess(raw,page.url()).status==='blocked')return {url:page.url(),raw,...assess(raw,page.url())};const close=page.getByRole('button',{name:/^(Close|إغلاق|اغلاق)$/i});if(await close.count()){await close.first().click({timeout:2000}).catch(()=>{});}
if(opts.waitFor)await page.waitForFunction(re=>new RegExp(re,'i').test(document.body?.innerText||''),opts.waitFor,{timeout:opts.wait||8000}).catch(()=>{});await page.waitForTimeout(opts.settle||1200);raw=await page.locator('body').innerText();if(opts.aria){const extra=await page.evaluate(re=>[...new Set([...document.querySelectorAll('[aria-label]')].map(e=>e.getAttribute('aria-label')||'').filter(x=>new RegExp(re,'i').test(x)&&x.length<120))].slice(0,10),opts.aria).catch(()=>[]);if(extra.length)raw=extra.join('\n')+'\n'+raw;}const result=await page.evaluate(()=>({title:document.title,text:document.body.innerText,links:[...document.querySelectorAll('a[href]')].map(a=>({url:a.href,label:a.innerText.slice(0,160)})).filter(a=>/^https?:/.test(a.url)).slice(0,120)}));return {...result,url:page.url(),raw,...assess(raw,page.url())};}finally{await context?.close().catch(()=>{});}}
export function cleanVisible(text){return String(text||'').split('\n').map(x=>x.trim()).filter(x=>x&&!/^(Log [Ii]n|Log in to Facebook|Forgot (?:Account|password)\??|Email or phone(?: number)?|Password|Create new account|or|More|Posts|About|Reels|Photos|Reload page|تسجيل الدخول|إنشاء حساب جديد)$/i.test(x)&&!/^See more from |^This page isn't available|^This may be because of a technical error|^Log in or sign up for Facebook|^Join Facebook|^Connect with /i.test(x)).join('\n');}
export function usefulLinks(links){return (links||[]).filter(l=>{try{const u=new URL(l.url);return !/\/(?:login|recover|reg|privacy|policies|help|settings|brand|sharer|share)(?:\/|$)/.test(u.pathname)&&!u.searchParams.has('login_attempt');}catch{return false;}});}
// ---- Platforms that hide public data from anonymous visitors ----
// Facebook pages: the official Page Plugin (the embed websites use) shows the page info and its latest
// public posts without logging in, while facebook.com itself often answers with a login wall.
export function fbPluginURL(value){try{const u=new URL(value);if(!/(^|\.)facebook\.com$/.test(u.hostname))return '';const seg=u.pathname.split('/').filter(Boolean);let page='';
 if(seg[0]==='profile.php'&&u.searchParams.get('id'))page='profile.php?id='+u.searchParams.get('id');
 else if(seg[0]==='pages'&&seg.length>=3)page=seg.slice(0,3).join('/');
 else if(seg.length===1&&!/^(?:posts|reel|reels|watch|groups|events|photo|photo\.php|story\.php|share|sharer|login|plugins|people|permalink\.php|marketplace|hashtag|search|help|policies|privacy|business|ads)$/i.test(seg[0]))page=seg[0];
 else if(seg.length===2&&/^(?:about|posts|videos|photos|reviews|community|mentions)$/i.test(seg[1]))page=seg[0];
 if(!page)return '';return 'https://www.facebook.com/plugins/page.php?href='+encodeURIComponent('https://www.facebook.com/'+page)+'&tabs=timeline&width=500&height=4000&small_header=false&hide_cover=true&show_facepile=false&locale=ar_AR';}catch{return '';}}
export function instagramUser(value){try{const u=new URL(value);if(!/(^|\.)instagram\.com$/.test(u.hostname))return '';const seg=u.pathname.split('/').filter(Boolean);return seg.length===1&&!/^(?:p|reel|reels|explore|accounts|stories|direct|about|legal)$/i.test(seg[0])?seg[0]:'';}catch{return '';}}
export function xUser(value){try{const u=new URL(value);if(!/(^|\.)(?:x|twitter)\.com$/.test(u.hostname))return '';const seg=u.pathname.split('/').filter(Boolean);return seg.length>=1&&seg.length<=2&&/^[A-Za-z0-9_]{1,15}$/.test(seg[0])&&!/^(?:home|i|search|explore|intent|share|login|settings|hashtag)$/i.test(seg[0])?seg[0]:'';}catch{return '';}}
export function isMaps(value){try{const u=new URL(value);return /^(?:goo\.gl|maps\.app\.goo\.gl)$/.test(u.hostname)&&(u.hostname!=='goo.gl'||u.pathname.startsWith('/maps'))||/(^|\.)google\.[a-z.]+$/.test(u.hostname)&&u.pathname.startsWith('/maps')||/^maps\.google\./.test(u.hostname);}catch{return false;}}
const fmtNum=n=>Number(n||0).toLocaleString('en-US');
export function xProfileText(user){if(!user)return '';const j=user.joined?new Date(user.joined):null;return [`${user.name} (@${user.screen_name}) — حساب X`,user.description&&('النبذة: '+user.description),user.location&&('المكان: '+user.location),user.website?.url&&('الموقع: '+user.website.url),`${fmtNum(user.followers)} متابع · ${fmtNum(user.following)} يتابع · ${fmtNum(user.tweets)} تغريدة · ${fmtNum(user.likes)} إعجاب`,j&&!isNaN(j)?('انضم: '+j.toISOString().slice(0,7)):'',user.verification?.verified?'حساب موثّق':''].filter(Boolean).join('\n');}
// Optional logged-in reading. The owner sets these in Vercel → Environment Variables with a spare account;
// they are never sent to the app or returned in responses.
async function instagramLoggedIn(user,attempts,session=''){const sid=session||process.env.IG_SESSIONID;if(!sid)return null;try{const r=await fetch('https://i.instagram.com/api/v1/users/web_profile_info/?username='+encodeURIComponent(user),{headers:{'x-ig-app-id':'936619743392459','User-Agent':BROWSER_HEADERS['User-Agent'],Cookie:'sessionid='+sid},signal:AbortSignal.timeout(15000)});const d=await r.json().catch(()=>({}));const u=d?.data?.user;attempts.push({method:'instagram_login',status:u?'read':'unavailable',reason:u?'':'HTTP '+r.status});if(!u)return null;
 const posts=(u.edge_owner_to_timeline_media?.edges||[]).slice(0,12).map(e=>e.node).map(n=>`${n.taken_at_timestamp?new Date(n.taken_at_timestamp*1000).toISOString().slice(0,10):''} · ${n.is_video?'فيديو':'صورة'} · ${fmtNum(n.edge_liked_by?.count||n.edge_media_preview_like?.count)} إعجاب · ${fmtNum(n.edge_media_to_comment?.count)} تعليق\nhttps://www.instagram.com/p/${n.shortcode}/\n${String(n.edge_media_to_caption?.edges?.[0]?.node?.text||'').slice(0,600)}`);
 return {title:u.full_name,text:[`${u.full_name} (@${u.username}) — حساب Instagram`,u.biography&&('النبذة: '+u.biography),u.external_url&&('الرابط: '+u.external_url),u.category_name&&('التصنيف: '+u.category_name),`${fmtNum(u.edge_followed_by?.count)} متابع · ${fmtNum(u.edge_follow?.count)} يتابع · ${fmtNum(u.edge_owner_to_timeline_media?.count)} منشور`,posts.length?'آخر المنشورات:\n'+posts.join('\n\n'):''].filter(Boolean).join('\n'),links:u.external_url?[{url:u.external_url,label:'bio'}]:[],status:'read',reason:'',method:'instagram_login',coverage:'partial',limitations:['اتقرأ الحساب وآخر 12 منشور بحساب القارئ.']};}catch(e){attempts.push({method:'instagram_login',status:'unavailable',reason:e.message});return null;}}
// The public profile embed keeps working when Instagram rate-limits the profile page itself.
export async function instagramEmbed(user,attempts){try{const x=await browserPage('https://www.instagram.com/'+encodeURIComponent(user)+'/embed/',{waitFor:'متابع|followers',wait:9000,settle:800});const text=cleanVisible(x.raw||'').split('\n').filter(l=>!/^(?:عرض الملف الشخصي بالكامل على Instagram|View full profile on Instagram|Instagram|•)$/i.test(l)).join('\n');const ok=/متابع|followers/i.test(text);attempts.push({method:'instagram_embed',status:ok?'read':'unavailable',reason:ok?'':'التضمين ما عرضش بيانات الحساب'});return ok?{title:user,text:text+'\n(@'+user+') — حساب Instagram',links:[],status:'read',reason:'',method:'instagram_embed',coverage:'partial',limitations:['اتقرأ عدد المتابعين والمنشورات من تضمين الحساب العام؛ النبذة ومحتوى البوستات محتاجين سكرين شوت أو حساب قارئ (IG_SESSIONID).']}:null;}catch(e){attempts.push({method:'instagram_embed',status:'unavailable',reason:e.message});return null;}}
async function readSpecial(url,attempts,opts={}){
 const fb=fbPluginURL(url);
 if(fb){try{const x=await browserPage(fb,{waitFor:'متابع|followers|likes|إعجاب',wait:9000,settle:2500});const text=cleanVisible(x.raw||x.text||'');attempts.push({method:'facebook_plugin',status:text.length>60?'read':'unavailable',reason:text.length>60?'':'الصفحة مش متاحة في إضافة فيسبوك (ممكن تكون بروفايل شخصي أو مقيدة)'});if(text.length>60)return {url,title:x.title||'',text,links:usefulLinks(x.links),status:'read',reason:'',method:'facebook_plugin',coverage:'partial',limitations:['اتقرأت معلومات الصفحة وآخر منشوراتها العامة من إضافة فيسبوك الرسمية (Page Plugin)؛ مش كل البوستات.']};}catch(e){attempts.push({method:'facebook_plugin',status:'unavailable',reason:e.message});}return null;}
 const ig=instagramUser(url);
 if(ig){const viaLogin=await instagramLoggedIn(ig,attempts,opts.igSession);if(viaLogin)return {url,...viaLogin};try{let r,html='';for(const ua of ['WhatsApp/2.23.20.0','Twitterbot/1.0','facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)']){r=await fetch('https://www.instagram.com/'+encodeURIComponent(ig)+'/',{headers:{'User-Agent':ua,Accept:'text/html'},redirect:'manual',signal:AbortSignal.timeout(15000)});if(r.ok){html=await r.text();if(/og:description/.test(html))break;}}const $=cheerio.load(html);const m=n=>String($(`meta[property="${n}"],meta[name="${n}"]`).first().attr('content')||'').replace(/[\u200e\u200f]/g,'').trim();const title=m('og:title'),desc=m('description')||m('og:description');const ok=r.ok&&/Followers|متابع/i.test(desc);attempts.push({method:'instagram_preview',status:ok?'read':'unavailable',reason:ok?'':(r.status===429||r.status===302?'إنستجرام عامل حد مؤقت على عدد الطلبات (HTTP '+r.status+')؛ ضيف حساب إنستجرام للقارئ (IG_SESSIONID) أو سكرين شوت':'HTTP '+r.status)});if(!ok){const em=await instagramEmbed(ig,attempts);if(em)return {url,...em};}if(ok)return {url,title,text:[title,desc].filter(Boolean).join('\n'),links:[],status:'read',reason:'',method:'instagram_preview',coverage:'partial',fromMeta:true,limitations:['اتقرأ ملخص الحساب العام (المتابعين وعدد المنشورات والنبذة) بس؛ محتوى البوستات محتاج سكرين شوت.']};}catch(e){attempts.push({method:'instagram_preview',status:'unavailable',reason:e.message});}return null;}
 const xu=xUser(url);
 if(xu){try{const r=await fetch('https://api.fxtwitter.com/'+encodeURIComponent(xu),{signal:AbortSignal.timeout(15000),headers:{Accept:'application/json'}});const d=await r.json().catch(()=>({}));const ok=r.ok&&d?.user?.screen_name;attempts.push({method:'x_profile',status:ok?'read':'unavailable',reason:ok?'':(d?.message||'HTTP '+r.status)});if(ok)return {url,title:d.user.name,text:xProfileText(d.user),links:d.user.website?.url?[{url:d.user.website.url,label:'website'}]:[],status:'read',reason:'',method:'x_profile',coverage:'partial',limitations:['اتقرأت بيانات الحساب العامة (النبذة والمتابعين وعدد التغريدات)؛ التغريدات نفسها مش متاحة من غير تسجيل دخول.']};}catch(e){attempts.push({method:'x_profile',status:'unavailable',reason:e.message});}return null;}
 if(isMaps(url)){try{const target=(()=>{const u=new URL(url);if(/google\./.test(u.hostname)&&!u.searchParams.has('hl'))u.searchParams.set('hl','ar');return u.href;})();const opts={waitFor:'مراجع|review|تقييم|\\d[.,]\\d\\s*\\(',wait:12000,settle:2500,aria:'^\\s*[\\d.,]+\\s*(?:نجوم|نجمة|stars?)|^\\s*[\\d.,]+\\s*(?:مراجعة|مراجعات|تعليق|reviews?)'};let x=await browserPage(target,opts);
 // Google sometimes serves a reduced view without the review count; one more load usually brings it.
 if(!/\d[\d,]*\s*(?:مراجعة|مراجعات|reviews?)|\(\s*\d[\d,]*\s*\)/i.test(x.raw||''))x=await browserPage(target,{...opts,settle:4000}).catch(()=>x);const text=String(x.raw||'').split('\n').map(l=>l.replace(/[\u200e\u200f\uE000-\uF8FF]/g,'').trim()).filter(l=>/[\p{L}\p{N}]/u.test(l)&&!/^(?:مطاعم|الفنادق|نشاطات مقترَحة|محطات نقل عام|مواقف سيارات|صيدليات|ماكينات صرّاف آلي|تم الحفظ|الأحدث|تثبيت التطبيق|الاتجاهات|حفظ|مشاركة|إرسال إلى هاتف|المواقع القريبة|أعجبني|اقتراح تعديل|الطبقات|تسجيل الدخول)$/.test(l)).join('\n');const ok=text.length>120&&/\d[.,]\d/.test(text);attempts.push({method:'maps_browser',status:ok?'read':'unavailable',reason:ok?'':'خرائط جوجل ما عرضتش بيانات المكان'});if(ok)return {url:x.url||url,title:x.title||'',text,links:[],status:'read',reason:'',method:'maps_browser',coverage:'partial',limitations:['اتقرأ ملخص المكان من خرائط جوجل (التقييم والعدد والعنوان وأول المراجعات الظاهرة) بس.']};}catch(e){attempts.push({method:'maps_browser',status:'unavailable',reason:e.message});}return null;}
 return null;}
export async function readSource(input,opts={}){const url=await safeURL(input),attempts=[];
 const special=await readSpecial(url,attempts,opts);const finish=x=>({...x,text:String(x.text||'').slice(0,24000),links:usefulLinks(x.links),limitations:x.limitations||[],attempts,at:Date.now()});
 if(special&&special.method!=='facebook_plugin')return finish(special);
 const generic=await readGeneric(url,attempts);if(!special)return generic;
 // Facebook: page plugin (info + latest posts) plus whatever the normal page showed (intro, website link)
 const extra=generic.status==='read'?String(generic.text||'').split('\n').filter(l=>!special.text.includes(l.trim())).join('\n'):'';
 return finish({...special,text:special.text+(extra.trim()?'\n--- من صفحة فيسبوك نفسها ---\n'+extra:''),links:[...toLinks(special.links),...toLinks(generic.links)]});}
const toLinks=l=>Array.isArray(l)?l:[];
async function readGeneric(url,attempts){let result=null;try{const d=await fetchPage(url),x=cleanHTML(d.html,d.url);result={...x,url:d.url,rawText:d.html.slice(0,60000),...assess(x.text,d.url),method:'direct'};attempts.push({method:'direct',status:result.status,reason:result.reason});if(result.status==='blocked')return {...result,attempts};}catch(e){attempts.push({method:'direct',status:'unavailable',reason:e.message});}
const social=/(^|\.)(facebook|instagram|tiktok)\.com$/.test(new URL(url).hostname);
if(result?.status!=='read'||social){try{const x=await browserPage(url);attempts.push({method:'browser',status:x.status,reason:x.reason});if(x.status==='read')result={...x,rawText:x.raw.slice(0,60000),method:'browser'};else if(result?.status!=='read')result={...x,rawText:x.raw?.slice(0,60000)||'',method:'browser'};}catch(e){attempts.push({method:'browser',status:'unavailable',reason:e.message});}}
const partial=result?.status==='read'&&(social||result.fromMeta);const limitations=partial?['القراءة تغطي المحتوى العام الذي ظهر فقط؛ لا تثبت فحص كل البوستات أو الإعلانات.']:[];if(result?.status==='read'&&result.fromMeta)limitations.push('الصفحة ما عرضتش نص من غير تسجيل دخول؛ اتقرأ وصف الصفحة الرسمي (العنوان والنبذة) بس.');if(/This page isn.t available|technical error/i.test(result?.text||''))limitations.push('ظهرت بيانات تعريف الصفحة لكن فيسبوك لم يحمّل المنشورات في هذه المحاولة.');return {...(result||{url,status:'unavailable',text:'',reason:'تعذر قراءة المصدر'}),text:result?.status==='read'?cleanVisible(result.text).slice(0,24000):'',links:result?.status==='read'?usefulLinks(result.links):[],coverage:partial?'partial':'available_text',limitations,attempts,at:Date.now()};}
