import dns from 'node:dns/promises';
import ipaddr from 'ipaddr.js';
import * as cheerio from 'cheerio';
export const BROWSER_HEADERS={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36','Accept-Language':'ar,en;q=0.8'};
export function publicIP(address){try{const a=ipaddr.process(address);return a.range()==='unicast';}catch{return false;}}
export async function safeURL(value){const u=new URL(value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||(u.port&&!['80','443'].includes(u.port)))throw Error('Only public HTTP(S) URLs are supported');const host=u.hostname.replace(/^\[|\]$/g,'');if(host==='localhost'||host.endsWith('.local')||host.endsWith('.internal'))throw Error('Private address rejected');const ips=ipaddr.isValid(host)?[{address:host}]:await dns.lookup(host,{all:true});if(!ips.length||ips.some(x=>!publicIP(x.address)))throw Error('Private address rejected');u.hash='';return u.href;}
export async function fetchPage(url){for(let n=0;n<5;n++){url=await safeURL(url);const r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(12000),headers:{...BROWSER_HEADERS,Accept:'text/html,application/xhtml+xml,text/plain;q=0.9,*/*;q=0.8'}});if(r.status>=300&&r.status<400&&r.headers.get('location')){url=new URL(r.headers.get('location'),url).href;continue;}if(!r.ok)throw Error('HTTP '+r.status);if(!/text\/|application\/xhtml/.test(r.headers.get('content-type')||''))throw Error('Unsupported content type');const reader=r.body.getReader();let size=0,parts=[];for(;;){const x=await reader.read();if(x.done)break;size+=x.value.length;if(size>1500000){await reader.cancel();throw Error('Page too large');}parts.push(Buffer.from(x.value));}return {url,html:Buffer.concat(parts).toString('utf8')};}throw Error('Too many redirects');}
export function cleanHTML(html,url){const $=cheerio.load(html);const title=$('title').text().trim();const meta=[...new Set(['og:title','og:description','description'].map(n=>String($(`meta[property="${n}"],meta[name="${n}"]`).first().attr('content')||'').replace(/[\u200e\u200f]/g,'').trim()).filter(Boolean))];$('script,style,noscript,svg,nav,footer,form,input,select').remove();$('br').replaceWith('\n');$('p,div,article,section,h1,h2,h3,li').append('\n');const body=$('body').text().split('\n').map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean).join('\n');const text=body.length<400&&meta.length?[...meta,body].filter(Boolean).join('\n'):body;const links=[];$('a[href]').each((_,a)=>{try{const u=new URL($(a).attr('href'),url);if(/^https?:$/.test(u.protocol)&&!u.username&&!u.password)links.push({url:u.href,label:$(a).text().trim().slice(0,160)});}catch{}});return {title,text,meta,fromMeta:body.length<400&&meta.length>0,links:[...new Map(links.map(x=>[x.url,x])).values()].slice(0,80)};}
export function assess(text,url){const t=String(text||'');if(/you.re temporarily blocked|automated (?:queries|traffic)|verify you are human|captcha|checking your browser|unusual traffic/i.test(t))return {status:'blocked',reason:'الموقع طلب تحقق أو حظر القراءة الآلية'};const social=/(^|\.)(facebook|instagram)\.com$/.test(new URL(url).hostname);const useful=social?/(?:followers|متابع|Intro|نبذة|ريلز|Reels|Shared with Public|استشاري|عيادة|Clinic)/i.test(t)&&t.length>180:t.length>180;if(useful)return {status:'read',reason:''};return {status:'unavailable',reason:/log in|log into|sign in|تسجيل الدخول/i.test(t)?'ظهرت صفحة دخول بدون محتوى كافٍ':'لم يظهر محتوى كافٍ للتحليل'};}
export async function browserPage(url){const [{chromium:pw},{default:chromium}]=await Promise.all([import('playwright-core'),import('@sparticuz/chromium')]);const browser=await pw.launch({args:chromium.args,executablePath:await chromium.executablePath(),headless:true});try{const context=await browser.newContext({serviceWorkers:'block',acceptDownloads:false,userAgent:BROWSER_HEADERS['User-Agent'],locale:'ar-EG'});const validated=new Map();await context.route('**/*',async route=>{const req=route.request();if(!['GET','HEAD'].includes(req.method())||['image','media','font'].includes(req.resourceType()))return route.abort();try{const u=req.url();if(!validated.has(new URL(u).origin))validated.set(new URL(u).origin,await safeURL(u));await route.continue();}catch{await route.abort();}});const page=await context.newPage();await page.goto(await safeURL(url),{waitUntil:'domcontentloaded',timeout:25000});await page.locator('body').waitFor({timeout:8000});let raw=await page.locator('body').innerText();if(assess(raw,page.url()).status==='blocked')return {url:page.url(),raw,...assess(raw,page.url())};const close=page.getByRole('button',{name:/^(Close|إغلاق|اغلاق)$/i});if(await close.count()){await close.first().click({timeout:2000}).catch(()=>{});}
await page.waitForTimeout(1200);raw=await page.locator('body').innerText();const result=await page.evaluate(()=>({title:document.title,text:document.body.innerText,links:[...document.querySelectorAll('a[href]')].map(a=>({url:a.href,label:a.innerText.slice(0,160)})).filter(a=>/^https?:/.test(a.url)).slice(0,120)}));return {...result,url:page.url(),raw,...assess(raw,page.url())};}finally{await browser.close();}}
export function cleanVisible(text){return String(text||'').split('\n').map(x=>x.trim()).filter(x=>x&&!/^(Log [Ii]n|Log in to Facebook|Forgot (?:Account|password)\??|Email or phone(?: number)?|Password|Create new account|or|More|Posts|About|Reels|Photos|Reload page|تسجيل الدخول|إنشاء حساب جديد)$/i.test(x)&&!/^See more from |^This page isn't available|^This may be because of a technical error|^Log in or sign up for Facebook|^Join Facebook|^Connect with /i.test(x)).join('\n');}
export function usefulLinks(links){return (links||[]).filter(l=>{try{const u=new URL(l.url);return !/\/(?:login|recover|reg|privacy|policies|help|settings|brand|sharer|share)(?:\/|$)/.test(u.pathname)&&!u.searchParams.has('login_attempt');}catch{return false;}});}
export async function readSource(input){const url=await safeURL(input),attempts=[];let result=null;try{const d=await fetchPage(url),x=cleanHTML(d.html,d.url);result={...x,url:d.url,rawText:d.html.slice(0,60000),...assess(x.text,d.url),method:'direct'};attempts.push({method:'direct',status:result.status,reason:result.reason});if(result.status==='blocked')return {...result,attempts};}catch(e){attempts.push({method:'direct',status:'unavailable',reason:e.message});}
const social=/(^|\.)(facebook|instagram|tiktok)\.com$/.test(new URL(url).hostname);
if(result?.status!=='read'||social){try{const x=await browserPage(url);attempts.push({method:'browser',status:x.status,reason:x.reason});if(x.status==='read')result={...x,rawText:x.raw.slice(0,60000),method:'browser'};else if(result?.status!=='read')result={...x,rawText:x.raw?.slice(0,60000)||'',method:'browser'};}catch(e){attempts.push({method:'browser',status:'unavailable',reason:e.message});}}
const partial=result?.status==='read'&&(social||result.fromMeta);const limitations=partial?['القراءة تغطي المحتوى العام الذي ظهر فقط؛ لا تثبت فحص كل البوستات أو الإعلانات.']:[];if(result?.status==='read'&&result.fromMeta)limitations.push('الصفحة ما عرضتش نص من غير تسجيل دخول؛ اتقرأ وصف الصفحة الرسمي (العنوان والنبذة) بس.');if(/This page isn.t available|technical error/i.test(result?.text||''))limitations.push('ظهرت بيانات تعريف الصفحة لكن فيسبوك لم يحمّل المنشورات في هذه المحاولة.');return {...(result||{url,status:'unavailable',text:'',reason:'تعذر قراءة المصدر'}),text:result?.status==='read'?cleanVisible(result.text).slice(0,24000):'',links:result?.status==='read'?usefulLinks(result.links):[],coverage:partial?'partial':'available_text',limitations,attempts,at:Date.now()};}
